# Generated by Django 3.2.4 on 2021-10-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineOrder', '0002_onlineorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineorders',
            name='ordered_products',
        ),
        migrations.AddField(
            model_name='onlineorders',
            name='ordered_products',
            field=models.ManyToManyField(related_name='_OnlineOrder_onlineorders_ordered_products_+', to='OnlineOrder.OnlineOrders'),
        ),
    ]
