# Generated by Django 3.2.4 on 2021-10-25 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineOrder', '0005_auto_20211024_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorders',
            name='address',
            field=models.CharField(default=43226, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineorders',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
